"""Storage contracts consumed by application services."""

from typing import Protocol


class UserRepository(Protocol):
    async def check_user_with_phone_number(self, phone_number: str) -> bool: ...
    async def get_user_with_email(self, email: str) -> dict | None: ...
    async def get_user_with_id(self, user_id: str) -> dict | None: ...
    async def update_user(self, user_id: str, user: dict) -> dict: ...
    async def store_user(self, user: dict) -> dict: ...
    async def email_exists(self, value: str) -> bool: ...


class OrganizationRepository(Protocol):
    async def get_organization_by_id(self, organization_id: str) -> dict | None: ...
    async def update_organization(
        self, organization_id: str, organization: dict
    ) -> dict: ...
    async def store_organization(self, organization: dict) -> dict: ...
    async def email_exists(self, value: str) -> bool: ...
    async def website_exists(self, value: str) -> bool: ...


class MembershipRepository(Protocol):
    async def get_org_membership(self, user_id: str) -> dict | None: ...
    async def check_org_ownership(self, organization_id: str, user_id: str) -> bool: ...
    async def store_org_membership(
        self, organization_id: str, user_id: str
    ) -> None: ...


class ResourceRepository(Protocol):
    async def get_resource_by_user_id(self, user_id: str) -> dict | None: ...
    async def update_by_user_id(self, user_id: str, resource: dict) -> dict: ...
    async def store_resource(self, resource: dict) -> dict: ...
    async def portfolio_exists(self, value: str) -> bool: ...
    async def linkedin_exists(self, value: str) -> bool: ...


class RefreshTokenRepository(Protocol):
    async def store_refresh_token(
        self, user_id: str, refresh_token: str, *, expires_at: int
    ) -> None: ...
    async def blacklist_refresh_token(self, refresh_token: str) -> None: ...
    async def check_refresh_token_valid(self, refresh_token: str) -> bool: ...


class AuditLogRepository(Protocol):
    async def store_audit_log(self, audit_log: dict) -> dict: ...


class AccessTokenRevocationStore(Protocol):
    async def revoke(self, raw_token: str, *, expires_at: int) -> None: ...
    async def is_revoked(self, raw_token: str) -> bool: ...
