"""Storage contracts consumed by application services."""

from typing import Protocol


class UserRepository(Protocol):
    async def check_user_with_phone_number(self, phone_number: str) -> bool: ...
    async def get_user_with_email(self, email: str) -> dict | None: ...
    async def get_user_with_id(self, user_id: str) -> dict | None: ...
    async def update_user(self, user_id: str, user: dict) -> dict: ...
    async def list_organization_users(self, organization_id: str) -> list[dict]: ...
    async def email_exists(self, value: str) -> bool: ...


class OrganizationRepository(Protocol):
    async def get_organization_by_id(self, organization_id: str) -> dict | None: ...
    async def update_organization(
        self, organization_id: str, organization: dict
    ) -> dict: ...
    async def email_exists(self, value: str) -> bool: ...
    async def website_exists(self, value: str) -> bool: ...


class PermissionRepository(Protocol):
    async def has_effective_permission(
        self, user_id: str, permission_key: str
    ) -> bool: ...
    async def list_effective_permissions(self, user_id: str) -> list[str]: ...


class MembershipRepository(Protocol):
    async def get_org_membership(self, user_id: str) -> dict | None: ...
    async def check_org_ownership(self, organization_id: str, user_id: str) -> bool: ...
    async def check_org_membership(
        self, organization_id: str, user_id: str
    ) -> bool: ...


class ResourceRepository(Protocol):
    async def get_resource_by_user_id(self, user_id: str) -> dict | None: ...
    async def update_by_user_id(self, user_id: str, resource: dict) -> dict: ...
    async def portfolio_exists(self, value: str) -> bool: ...
    async def linkedin_exists(self, value: str) -> bool: ...


class RefreshTokenRepository(Protocol):
    async def store_refresh_token(
        self, user_id: str, refresh_token: str, *, expires_at: int
    ) -> None: ...
    async def blacklist_refresh_token(self, refresh_token: str) -> None: ...
    async def check_refresh_token_valid(self, refresh_token: str) -> bool: ...


class OnboardingRepository(Protocol):
    async def onboard_organization(self, params: dict) -> dict: ...
    async def onboard_resource(self, params: dict) -> dict: ...


class ProjectRepository(Protocol):
    async def store_project(self, project: dict) -> dict: ...
    async def get_project_by_id(self, project_id: str) -> dict | None: ...
    async def publish_draft(
        self,
        project_id: str,
        published_at: str,
        *,
        embedding: list[float] | None,
        embedding_model: str | None,
        embedded_at: str | None,
        organization_id: str | None,
    ) -> dict | None: ...


class AuditLogRepository(Protocol):
    async def store_audit_log(self, audit_log: dict) -> dict: ...


class AccessTokenRevocationStore(Protocol):
    async def revoke(self, raw_token: str, *, expires_at: int) -> None: ...
    async def is_revoked(self, raw_token: str) -> bool: ...


class OrganizationUsersCache(Protocol):
    async def get(self, organization_id: str) -> list[dict] | None: ...
    async def set(self, organization_id: str, users: list[dict]) -> None: ...
